// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gmqknbtirwarrowerpzj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdtcWtuYnRpcndhcnJvd2VycHpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3MDEzMjcsImV4cCI6MjA2ODI3NzMyN30.yhH4DsGwOYWXLwTQQL6pEkwf5mRT4dB9N4LBD6E9xHs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});